### ISSUE TITLE
galaxy API

### ISSUE THREAD

**Issue by 5inghalp** [dk000000000/von-neumann-probe-simulation#4]
class galaxy(numsystems,numagent) #number of systems, number of agents:
   self.step(actionD) #dictionary of action increment self.time and will return false self.timelimit is met, check_block() to block agent to act if it is blocked
       return #boolean if is out of time limit
   self.reset() # reset the galaxy, kill everyone
   self.agentlist = {} dictionary of agents
   self.systemlist = [] list of system
   self.time # current time since the start
   self.timelimit # max numer of time can take
   
  self.check_block()
  self.render() #render what is hapenning in galaxy

**Comment by dk000000000** [comment]
mostly done, still some bugs
